name: Sync readings to almo7aya.dev

on:
  push:
    branches:
      - master
  schedule:
    # Adjust refresh schedule here. By default, it runs once per day.
    # Syntax reference: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule
    # Recommended tool: https://crontab.guru/
    - cron: "30 * * * *"

jobs:
  get_bin_from_release_and_exec:
    runs-on: ubuntu-latest
    steps:
      - run: |
          wget https://github.com/Almo7aya/reading-syncer/releases/download/v0.0.4/reading-syncer-linux-amd64
          chmod +x ./reading-syncer-linux-amd64
          ./reading-syncer-linux-amd64 ${{secrets.GIT_TOKEN}} ${{secrets.NOTION_TOKEN}} ${{secrets.NOTION_DB_ID}} 

