name: Sync reading to almo7aya.dev

on:
  push:
    branches:
      - master
  schedule:
    # Adjust refresh schedule here. By default, it runs once per day.
    # Syntax reference: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule
    # Recommended tool: https://crontab.guru/
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: suisei-cn/actions-download-file@v1.0.1
        with:
          url: https://github.com/Almo7aya/reading-syncer/releases/download/v0.0.1/reading-syncer-linux-amd64
          target: ./bin

  exec:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: | 
          chmod +x ./bin/reading-syncer-linux-amd64
          ./bin/reading-syncer-linux-amd64 gh_token=${{secrets.GIT_TOKEN}} notion_token=${{secrets.NOTION_TOKEN}} notion_database_id=${{secrets.NOTION_DB_ID}}


