name: Sync readings to almo7aya.dev

on:
  push:
    branches:
      - master
  schedule:
    # Adjust refresh schedule here. By default, it runs once per day.
    # Syntax reference: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule
    # Recommended tool: https://crontab.guru/
    - cron: "0 0 * * *"

jobs:
  get_bin_from_release_and_exec:
    runs-on: ubuntu-latest
    steps:
      - env:
            GH_TOKEN_ENV: ${{ secrets.GIT_TOKEN }}
            NOTION_TOKEN_ENV: ${{ secrets.NOTION_TOKEN }}
            NOTION_ID_ENV: ${{ secrets.NOTION_ID }}
        run: |
          wget https://github.com/Almo7aya/reading-syncer/releases/download/v0.0.2/reading-syncer-linux-amd64
          chmod +x ./reading-syncer-linux-amd64
          ./reading-syncer-linux-amd64 notion_token=$NOTION_TOKEN_ENV notion_database_id=$NOTION_ID_ENV gh_token=$GIT_TOKEN_ENV

